baseURL: 'https://blog.scarpellini.dev'
title: My blog
paginate: 5
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpored: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: My blog
  description: test
  author: Gianluca Scarpellini

  ShowReadingTime: true
  ShowShareButtons: true
  comments: false
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    # imageUrl: '<img location>'
    # imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: Hi there
    Content: "Welcome to my blog \U0001F44B"

  socialIcons:
    - name: github
      url: 'https://github.com/gianscarpe'
    - name: linkedin
      url: 'https://www.linkedin.com/in/gianlucascarpellini/'

      
