baseURL = "https://blog.scarpellini.dev"
languageCode = "en-us"
title = "Cactus ideas"
theme = "cactus"
copyright = "Gianluca Scarpellini" # cactus will use title if copyright is not set
disqusShortname = "https://blog.scarpellini.dev" # Used when comments is enabled. Cactus will use site title if not set
googleAnalytics = "G-LSYX69L8TB"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Short stories"
url = "/Short stories"
weight = 5

[[menu.main]]
name = "Donate"
url = "https://www.paypal.com/donate?business=A4GM8S9EB4ZUN&no_recurring=0&item_name=I%27m+glad+you+decided+to+offer+me+a+beer%21+&currency_code=EUR"
weight = 6

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Resume"
url = "https://github.com/gianscarpe/resume/blob/master/Gianluca_Scarpellini_CV.pdf"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Hi there! My name is Gianluca Scarpellini and I'm a PhD student at the Italian Institute of Technolgy. I'm passionate about computer vision, research, and books!"
  showAllPostsOnHomePage = true # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default
  showReadTime = true # default

  [params.comments]
    enabled = true # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/gianscarpe"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/gianscarpellini"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/gianlucascarpellini"
  [[params.social]]
    name = "email"
    link = "gianluca@scarpellini.dev"  # no need for "mailto:" in the head

[[params.social]]
    name = "goodreads"
    link = "https://www.goodreads.com/user/show/123225277-gianscarpe"  # no need for "mailto:" in the head
