baseURL: 'https://blog.scarpellini.dev'
title: My blog
paginate: 5
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpored: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true


menu:
  main:
    - name: Tags
      url: /tags/
      weight: 10  
    - name: Posts
      url: /posts/
      weight: 1 
    - name: Research
      url: /research/
      weight: 2

  
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: My blog
  description: test
  author: Gianluca Scarpellini

  ShowReadingTime: true
  ShowShareButtons: true
  comments: false
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: My blog
    # imageUrl: '<img location>'
    # imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
      - name: Research
        url: research

  homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about...
            
  socialIcons:
    - name: github
      url: 'https://github.com/gianscarpe'
    - name: linkedin
      url: 'https://www.linkedin.com/in/gianlucascarpellini/'

      
