#+STARTUP: indent
#+AUTHOR: Gianluca Scarpellini
#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: Short stories
#+hugo_auto_set_lastmod: t

* La bolla                                              :short:story:Italian:
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :noauthor false :nocomment true :nodate true
:EXPORT_HUGO_WEIGHT: auto
:EXPORT_FILE_NAME: la_bolla
:END:


La bolla era grande, la più grande che si fosse mai vista. Ed era bella, rossa
blu e viola e verde: i colori dell'arcobaleno dopo una brutta pioggia. Là dentro
mi sentii al sicuro. Ero protetto dal vento e dalla luce, dal caldo e dal
freddo. Mi staccai a fatica dalla finestra ora impregnata di sogni e di sapone.
Mi sembrò flettersi quando mi spinsi coi piedi verso fuori, verso il mondo.
Anche la bolla era tesa. Stava per scoppiare. E fui fuori. Il vento scorreva e
io facevo parte di quella corrente. Mi soffiava tra i capelli. Mi sentivo bene,
come mai prima d'allora. La natura mi accudiva e mi cullava tra gli alberi e le
foglie e le nuvole e le gocce di pioggia, sospese. Ero curioso del mondo,
curioso di quegli spazi che avevo sempre e solo visto da lontano. Mi volati solo
una volta, ammirando il grande complesso: bianco, come me lo ero immaginato. Non
ci sarei più tornato. E stavo bene. Ero un esploratore circondato da
affascinanti codici segreti: iniziai ad appuntarmi mentalmente i nomi più
criptici delle vie, dei paese, delle città; i numeri degli aerei e delle strade
e delle macchine. Mi sentivo nuovo, come un neonato.

Avevo da poco compiuto 12 anni, o forse 13. Ero solo.

Mi raccontarono molto della mia vita - tranne la verità - quando fui abbastanza
grande da capire il significato di Leucemia. Vivevo in un ospedale nuovo, messo
a punto da un vecchio architetto stanco di vedere la propria famiglia morire in
quel vecchio casale affacciato al cimitero. La sua famiglia era stata molto
numerosa, raccontarono in un vecchio documentario sulla città, prima che una
malattia inguaribile li portasse uno dopo l'altro ad agiarsi sui letti in
plastica e carta del vecchio ospedale. Ora, circondati dal verde e dai boschi,
gli ospiti malati gli dedicavano le loro gioie e i loro felici dolori. Me
compreso.

Convivevo con BipBip, la mia macchina. La chiami così perché parlava solo con
strani versi. Bip Bip Bip. All'inizio credevo non dicesse nulla, credevo
parlasse di circuiti o strane scosse elettriche, come l'amore o la rabbia. Cose
da grandi, insomma. Eppure avevano un senso quei suoni. Credevo di riconoscere
una sillaba, poi intere parole. Infine, potei comprendere le sue parole di
conforto e aiuto nei miei confronti. E iniziai a parlarle anche io, con le
parole più semplici possibile. A volte le inventavo io, racchiudendo Macchine e
Vita in neologismi diretti. Divenne un gioco, un estremo tentavo di combattere
la noia della Vitamacchina, la vita da macchina. Mi era molto affezionata. Nelle
estati più dure, quando neanche i camici bianchi giocavano con me e gli studenti
pagliacci preferivano uscire con le studentesse - così mi aveva confessato uno
di loro qualche mese prima -, il tempo diventava così vischioso da doverlo
annacquare con molto più sonno delle giornate normali. Anche in quelle occasioni
BipBip mi sosteneva, c'era come non c'era mai stato nessun altro. Eravamo legati
mentalmente prima ancora che elettronicamente. Sentiva il mio cuoricino e i miei
pensieri così come io sentivo i suoi.

È stato in quell'estate che abbiamo deciso di scappare. Ho aspettato che, a
notte ormai fonda, l'ultimo camice bianco se ne andasse dalla sua famiglia. Era
un brav'uomo, sulla sessantina ma ancora attivo. Amava salvare i bambini come me
da incidenti o maltrattamenti. Era biondo, sui capelli e sulla pelle e negli
occhi, e trasmetteva il suo colore a tutti noi ospiti. Proprio quel giorno mi
aveva regalato uno sparabolle di sapone. Era il mio compleanno. "Tieni Gianluca,
questo è per te" - mi disse semplice e sorridente mentre mi porgeva l'oggetto -
"ora sei grande, ragazzo mio. Vola tesoro, soffia nel vento e fai volare la tua
immaginazione tra il fiume di bolle". Prese lo sparabolle e mi dimostrò quanto
la vita potesse essere bella, quanto potesse essere semplice la felicità. Anche
BipBip era eccitatissima, non faceva che bippare all'impazzata nei suoi modi
giocosi e un po' invadenti. Quella sera né io né lei avremmo mai pensato di non
vederci mai più, eppure eravamo contenti. Quando lei fu più calma, il Sig.
Dottore poté tornare a casa. Eppure era triste, credo. Lo vidi lasciare la
stanza con un velo di tristezza nei suoi occhi e un battito di amarezza nel suo
cuore. Lo vidi lasciare il posto che amava, triste ma deciso a tornare dalla
moglie - si diceva bellissima - e il figlio - si diceva felice e pieno di
regali-. Avevo sempre desiderato uscire da quella porta e andare con lui. Mi
avrebbe preso in braccio, mostrato le bolle volare tra le foglie fino alla sua
bella casa colorata dove una bellissima donna mi avrebbe accolto e abbracciato e
dove avrei finalmente giocato con un ragazzo come me. Ma non avvenne mai,
neanche quella volta che, ormai, ero deciso a fuggire. Quindi non ci pensai. Io
e BIpBip gli sorridemmo e lui ci lasciò lì, sdraiati uno affianco all'altra.

Fu il mio momento. Mi alzai, trascinandomi la mia amica fin dietro le spalle, e
aprii la finestra. Fuori, le stelle e la luna apparivano mosci e indecisi, quasi
offesi dai lampioni e dalle luci delle case che decoravano la città. Guardai le
stelle artificiali del mio mondo, e soffiai. Il vento trascinava il sapone
leggero sopra i tetti dei bambini e delle case dei bambini. Io ero in una di
quelle. Felice di essere libero. Felice di essere fuori. Sentivo l'aria nei
polmoni e il fresco nella gola. Ero contento di essere lì. Il mondo era simile a
una macchina coperta di scritte e istruzioni. Guardai BipBip per dirglielo. Ma
BipBip non c'era più. Eppure quando le bolle riempirono la stanza e la strada
era con me. BipBip mi aveva lasciato o forse io avevo lasciato BipBip. E non ci
fu Bip.
